### ISSUE TITLE
Running with many CSV traces is causing Segmentation Fault

### ISSUE THREAD

**Issue by michaelpekala-gtri** [SamueleGerminiani/harm#1]
Running HARM with more and more CSV traces increases the probability of a segmentation fault occurring during execution. 

With <150 traces, HARM might crash 20% of the time.
With >1000 traces, HARM might crash 98% of the time.

This is likely related to the multi-thread processing functionality of the program and involve race-conditions or deadlocks because the following execution will not cause a crash:

`harm --csv-dir {my_csv_dir} --clk clk --conf {my_harm_config_dir}/harm_config.xml --max-threads 1`

Removing the `--max-threads` limit causes possible crashes to occur again.

`harm --csv-dir {my_csv_dir} --clk clk --conf {my_harm_config_dir}/harm_config.xml`

**Comment by SamueleGerminiani** [comment]
Hi @michaelpekala-gtri 
The number of traces used as input likely has nothing to do with race conditions. Threads share only read-only memory, and everything else is duplicated to avoid issues such as false sharing, which can significantly reduce performance. Could you share your input so I can reproduce the error? Also, what version of harm are you using—was it compiled from source, or are you using the Docker image?

**Comment by michaelpekala-gtri** [comment]
[csv.zip](https://github.com/user-attachments/files/18132921/csv.zip)
[harm_config.txt](https://github.com/user-attachments/files/18132926/harm_config.txt)

I built on version `0511e0a`.

I ran with the following command: `harm --csv-dir csv/ --clk clk --conf harm_config.xml`

I have attached a .txt file since Github will not let me upload .xml files.

**Comment by SamueleGerminiani** [comment]
You are using an extremely old version of harm. I recently released v2, in which several bugs were fixed. I suggest upgrading to the latest commit. I tested your example on 10 runs with the latest version, and none of them crashed. Please read the README.md to see the changes of v2: some options have changed; for example, in your XML, you are using dtLimits option 'R' that became 'U' in v2.
